### ISSUE TITLE
Improve Crawler so it can fetch quotes in Spanish 

### ISSUE THREAD

**Issue by viniciusarre** [viniciusarre/quote-a-lang-crawler#13]
This issue would require to write one more case in which the crawler would fetch quotes (as it currently happen in French), but using the [Spanish-language site ](https://es.wikiquote.org/wiki/Portada) in order to bring the newly fetch quotes and then save it to the database.

There's already an implemented flow, for fetching quotes in French... feel free to follow through with it, or I'd love to hear any thoughts you might on improving it.

**Comment by Conor0Callaghan** [comment]
Maybe we can parameterise the chosen language and have a supported list of languages it can poll/retrieve data for?

**Comment by viniciusarre** [comment]
@ivernus, thank you for your interest in this repository! 

Yes, this is the plan for the future. For now it needs fetching data for languages directly, since it still relies on a crawler which needs explicit code for fetching for each language. But as we have a set of languages, the ideal logic is to automatically implement a language flow...
