### ISSUE TITLE
Improve Crawler so it can fetch quotes in English

### ISSUE THREAD

**Issue by viniciusarre** [viniciusarre/quote-a-lang-crawler#6]
This issue would require to write one more case in which the crawler would fetch quotes (as it currently happen in French), but using the [English-language site ](https://en.wikiquote.org/wiki/Main_Page) in order to bring the newly fetch quotes and then save it to the database. 

There's already an implemented flow, feel free to follow through with it, or I'd love to hear any [thoughts you might on improving it. ](https://github.com/viniciusarre/quote-a-lang-crawler/issues/3)

**Comment by manangoel99** [comment]
I'd like to work on this issue

**Comment by viniciusarre** [comment]
Hey @manangoel99, thank you for your interest in this project! I'd love to review your PR in the future! Let me know if you have any questions or suggestions!

**Comment by manangoel99** [comment]
Will I also have to set up a mongodb server on my system?

Figured it out. I set up a mongo server and got the script working.

**Comment by viniciusarre** [comment]
Great!

I also updated the project's README in order to include a quick way to set it up with docker...

**Comment by lexiewh** [comment]
Hi! I can also work on this issue as well. Or if you'd like I can work on another element as well. Just let me know.

**Comment by viniciusarre** [comment]
Hi @lexiewh, I'm really sorry for the late reply! I have been a bit busy this week!

Thank you for your interest in working in this project, I will create an issue in order to approach a new (but similar) problem: we need to fetch quotes in other languages as well (not only English and French).

Please, check the #13 for further details

Thanks again for your interest! I look forward to reviewing your contributions!
