### ISSUE TITLE
Add tests for crawler

### ISSUE THREAD

**Issue by viniciusarre** [viniciusarre/quote-a-lang-crawler#7]
Make sure that the crawler fetches properly the quotes, including, language, author and source before saving it to the database

**Comment by oktak** [comment]
Let me take this.

I think `Fetch_Fr()` in [fr.py](https://github.com/viniciusarre/quote-a-lang-crawler/blob/master/dev/fetch/fr.py) may need to separate fetch data and write to DB in two steps in order to test the result against with the web page.

**Comment by viniciusarre** [comment]
Hi, @oktak 
Thank you for your interest in this repository! 
Maybe this can be solved by adding `Fetch_Fr(self, soup, url_name, save_to_db = true)` and then pass `save_to_db` as `false` during tests... what do you think?

**Comment by oktak** [comment]
Oh! It is a great idea! 
Just modified the code. Please have a look. :smiley: 

The way to run the test code:
```bash
python3 -m unittest tests/Test_crawler.py
```
